export const ERROR_CODES = {
    UNAUTHORIZED: "UNAUTHORIZED",
    FORBIDDEN: "FORBIDDEN",
    NOT_FOUND: "NOT_FOUND",
    BAD_REQUEST: "BAD_REQUEST",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    CONFLICT: "CONFLICT",
    SLUG_TAKEN: "SLUG_TAKEN",
    INTERNAL_ERROR: "INTERNAL_ERROR",
  } as const;
  
  export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
  